Bump the ansible-lint version to 24.7.0
ansible/cloud-content-ci-automation pull request #3
Opened 2024-07-22 20:04 UTC by mandar242

Bump the ansible-lint version to 24.7.0

2024-07-23 13:39 UTC, gravesm approved these changes

2024-07-24 17:09 UTC, gravesm approved these changes

2024-07-26 19:02 UTC, GomathiselviS requested changes
Can you update the version in the tool's README?

2024-07-26 19:11 UTC, hakbailey approved these changes

2024-07-26 19:15 UTC, GomathiselviS approved these changes

2024-07-26 19:15 UTC, merged